Fix unused pthread_types
unused since 0706211c

in my text editor, this causes:

```console
$ babi t.cpp
...
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/babi/highlight.py", line 563, in _include
    return self._patterns(grammar, (repository[s[1:]],))
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/babi/fdict.py", line 44, in __getitem__
    raise KeyError(key)
KeyError: 'pthread_types'
```